### ISSUE TITLE
environment.yml can't be solved 

### ISSUE THREAD

**Issue by ncclementi** [coiled/examples#6]
I was not able to create an environment with the `environment.yml`. There is a conflict due to an array pin on pandas. 

```
>>>  mamba env create -f environment.yml -n coiled-examples
Looking for: ['python==3.10', 'dask', 'dask-ml', 'coiled', 'pyarrow', 's3fs', 'matplotlib', 'ipykernel', 'dask-labextension', 'xgboost', 'pandas=2', 'optuna', 'xarray', 'geogif', 'zarr', 'pip']

Could not solve for environment specs
Encountered problems while solving:
  - package xarray-2023.1.0-pyhd8ed1ab_0 requires pandas >=1.3,<2a0, but none of the providers can be installed
``` 

I tried installing pandas 2.0 with pip and I was able to do it locally, and then get the right pandas version on the cluster, despite having a package sync error. (I opened an issue on platform https://github.com/coiled/platform/issues/1187)

![Screen Shot 2023-04-12 at 11 35 22 AM](https://user-images.githubusercontent.com/7526622/231508478-d6e2259d-2d7e-4a33-a05f-9d408cfa5641.png)

I ran the geospatial example that uses xarray and it works. If we are ok with the error showing but things running, I opened a PR that makes the env file install pandas with pip. 
Otherwise, you'll want to use separate envs.

**Comment by mrocklin** [comment]
We don't really have a motivating geospatial example just yet.  I'm also fine removing it and xarray for the short term.

**Comment by ncclementi** [comment]
Closing this as now xarray new release works with pandas 2.0
